Split up ES and health inputs, fix calculations, and also split up it…
PsychicMuffin/PathOfDamage pull request #89
Opened 2017-06-27 19:30 UTC by ficocelliguy

…ems into sections. Fixes #88, fixes #85, fixes #82

2017-06-27 22:51 UTC, PsychicMuffin requested changes

2017-06-27 22:51 UTC, PsychicMuffin commented on js/DataService.js
>            manaPool: 1000,
probably should just change this to mana to be consistent

2017-06-27 22:51 UTC, PsychicMuffin commented on js/Items.js
> +          this.getMobModifiers()
I grouped mob modifiers for convenience earlier, but now we'll need monster increased and monster more to be separate

2017-06-27 22:51 UTC, PsychicMuffin commented on js/app.js
> +      while (calc.healthRemaining + calc.esRemaining > 0 && l++ < 1000) {
this will bug out when we implement taking damage of all types, which will cause chaos damage to bypass ES without a certain flag set. Although I guess the max survivable hit is always physical for now, you get the idea, it can just be health remaining instead of both.

2017-06-27 22:51 UTC, PsychicMuffin commented on js/app.js
> +      var l = 0;
I know this doesn't apply to JS scope, but shouldn't we place l outside the loop to be clear about its scope? Also, could we name it maxCalcs or something so its purpose is clearer?

2017-06-27 22:51 UTC, PsychicMuffin commented on js/Items.js
> +      return sort(
The point of splitting this up was for each section to function like quick add of its own category. We should either add that to this pull request or not mark the issue fixed.

2017-06-28 02:07 UTC, ficocelliguy commented on js/Items.js
> +      return sort(
//TODO

2017-06-28 02:07 UTC, ficocelliguy commented on js/Items.js
> +          this.getMobModifiers()
//TODO

2017-06-28 02:20 UTC, PsychicMuffin approved these changes

2017-06-28 02:21 UTC, merged